
apiVersion: extensions/v1beta1
kind: Deployment
metadata:  
  name: caddy
  namespace: consul-test
  labels:
    app: caddy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image:  dalongrong/caddy-node-build
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090

--- 
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: consul-test
  labels:
    app: caddy
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: caddy
  selector:
    app: caddy